version: '2'
services:
    solr:
        image: solr:5.5.3-alpine
        environment:
        - SOLR_HOME=/home/mysolrhome
        ports:
        - 8983:8983
        volumes:
        - ./solr-config:/home/mysolrhome
#        - ./solr-config/data:/home/mysolrhome/mapping/data
        command: ["solr", "-f"]
    neo4j:
        image: neo4j:3.1.1
        environment:
        - NEO4J_AUTH=neo4j/dba
        cap_add:
         - SYS_RESOURCE
        ports:
        - 7474:7474
        - 7687:7687
    oxo:
        image: oxo:latest
        depends_on:
        - neo4j
        - solr
        links:
            - neo4j
            - solr
        environment:
        - spring.datasource.url=jdbc:hsqldb:file:/home/hsqldb
        - oxo.neo.driver=org.neo4j.ogm.drivers.http.driver.HttpDriver
        - oxo.neo.uri=http://neo4j:dba@neo4j:7474
        - spring.data.solr.host:http://solr:8993/solr
        command:
            - java
            - -jar
            - /home/oxo.jar
        ports:
        - 8080:8080