version: '2'
services:
    solr:
        extends:
          file: docker-compose.common.yml
          service: solr
    neo4j:
        extends:
          file: docker-compose.common.yml
          service: neo4j
    oxo:
        build: oxo-web
        depends_on:
          - neo4j
          - solr
        links:
          - neo4j
          - solr
        environment:
          - spring.datasource.url=jdbc:hsqldb:file:/mnt/hsqldb
          - oxo.neo.driver=org.neo4j.ogm.drivers.http.driver.HttpDriver
          - oxo.neo.uri=http://neo4j:dba@neo4j:7474
          - spring.data.solr.host=http://solr:8983/solr
        volumes:
          - ./data/hsqldb:/mnt/hsqldb
        ports:
        - 8080:8080
