apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: oxo-{{ .Values.oxoRelease }}-solr-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
