apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: oxo-{{ .Values.oxoRelease }}-neo4jimport
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
