apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-neo4j
  labels:
    app: {{ .Release.Name }}-neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-neo4j
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:3.1.1
          imagePullPolicy: Always
          env:
              # - name: NEO4J_HEAP_MEMORY
              # value: 10g
              # - name: NEO4J_dbms_memory_heap_maxSize
              # value: 8g
            - name: NEO4J_AUTH
              value: neo4j/dba
          ports:
            - containerPort: 7474
            - containerPort: 7687
          volumeMounts:
            - name: {{.Release.Name}}-neo4jimport
              mountPath: "/var/lib/neo4j/import"
            - name: {{.Release.Name}}-neo4j-data
              mountPath: "/data"
      volumes:
      - name: {{.Release.Name}}-neo4jimport
        persistentVolumeClaim:
          claimName: {{.Release.Name}}-neo4jimport
      - name: {{.Release.Name}}-neo4j-data
        persistentVolumeClaim:
          claimName: {{.Release.Name}}-neo4j-data
